version: '3.9'

services:
  mysql:
    image: postgres:17
    container_name: ${COMPOSE_PROJECT_NAME}.db
    restart: unless-stopped
    networks:
      - app-network  
    volumes:
      - mysql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: ${COMPOSE_PROJECT_NAME}.redis
    networks:
      - app-network
   
volumes:
  mysql_data:
    name: ${COMPOSE_PROJECT_NAME}.mysql_data
    driver: local
networks:
  app-network:
    name: ${COMPOSE_PROJECT_NAME}-network